# When a PR get labelled "preview", deploy a web rendering of the changes via pushpreview
name: PushPreview

on:
  pull_request_target:
    types:
      - labeled

jobs:
  preview:
    runs-on: ubuntu-24.04
    if: github.event.label.name == 'preview'
    permissions:
      pull-requests: write  # Ensure permission to add comments
      contents: read        # Default for reading the repository contents
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          ref: ${{ github.head_ref }}
      - name: Comment
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body "⚙️ Hang tight! PushPreview is currently building your preview. We'll share the URL as soon as it's ready."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 18

      - name: Set BASE_URL
        run: echo "BASE_URL=/github/${{ github.repository }}/${{ github.event.number }}/" >> $GITHUB_ENV

      - name: Build site
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Generate preview
        uses: TechDocsStudio/pushpreview-action@cf958f7be2bf55d3f56d351bb9abf56b4c6b9a50 # 1.0.6
        with:
          source-directory: ./build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pushpreview-token: ${{ secrets.PUSHPREVIEW_TOKEN }}
